class AppLocalizations {
  static const Map<String, Map<String, dynamic>> _data = {
    'ta': {
      'name': 'தமிழ்',
      'holdToSpeak': 'பேச அழுத்திப் பிடிக்கவும்',
      'recording': 'கேட்கிறது...',
      'minimize': 'வரைபடத்திற்குச் செல்',
      'advisory': 'கடல்சார் ஆலோசனை',
      'guardrails': 'பாதுகாப்பு விதிகள் செயலில்',
      'details': 'விவரங்கள் ▴',
      'sampleQuestion': 'புயல் எச்சரிக்கை உள்ளதா? அருகிலுள்ள PFZ எங்கே?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'வானிலை பாதுகாப்பானது (அலை: 1.3 மீ, காற்று: 12.5 நாட்ஸ்). சிறந்த மீன்பிடி மண்டலம் PFZ-TN-04 14.2 கி.மீ தொலைவில் உள்ளது.',
      'sampleAnswerEn': 'Sea state is calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-TN-04 is 14.2 km away.',
      'borderStatus': 'சர்வதேச கடல் எல்லை (IMBL) 4.8 கி.மீ தொலைவில் உள்ளது. நீங்கள் பாதுகாப்பான இந்திய எல்லையில் உள்ளீர்கள்.',
      'borderStatusEn': 'IMBL is 4.8 km away. You are inside safe sovereign territorial waters.',
      'weatherStatus': 'அலை உயரம் 1.3 மீ, காற்று 12.5 நாட்ஸ். மீன்பிடிக்க கடல் ஏற்றதாக உள்ளது.',
      'weatherStatusEn': 'Wave height 1.3m, wind 12.5 kts. Optimal sea conditions for fishing.',
      'quickPrompts': ['🐟 அருகிலுள்ள PFZ', '⚠️ எல்லை சரிபார்', '🌊 அலைகள்', '🏠 துறைமுகம்'],
    },
    'te': {
      'name': 'తెలుగు',
      'holdToSpeak': 'మాట్లాడటానికి నొక్కి పట్టుకోండి',
      'recording': 'వింటున్నది...',
      'minimize': 'మ్యాప్‌కు వెళ్లండి',
      'advisory': 'సముద్ర సలహాదారు',
      'guardrails': 'రక్షణ నియమాలు చురుగ్గా ఉన్నాయి',
      'details': 'వివరాలు ▴',
      'sampleQuestion': 'తుఫాను హెచ్చరిక ఉందా? సమీప PFZ ఎక్కడ?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'సముద్రం ప్రశాంతంగా ఉంది (అలలు: 1.3 మీ, గాలి: 12.5 నాట్స్). అనుకూలమైన చేపల వేట ప్రాంతం PFZ-AP-02 14.2 కి.మీ దూరంలో ఉంది.',
      'sampleAnswerEn': 'Sea conditions calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-AP-02 is 14.2 km away.',
      'borderStatus': 'అంతర్జాతీయ సముద్ర సరిహద్దు (IMBL) 4.8 కి.మీ దూరంలో ఉంది. మీరు సురక్షిత భారతీయ జలాల్లో ఉన్నారు.',
      'borderStatusEn': 'IMBL boundary is 4.8 km away. Vessel is in safe Indian waters.',
      'weatherStatus': 'అలల ఎత్తు 1.3 మీ, గాలి 12.5 నాట్స్. వేటకు వాతావరణం అనుకూలంగా ఉంది.',
      'weatherStatusEn': 'Wave height 1.3m, wind 12.5 kts. Favorable conditions.',
      'quickPrompts': ['🐟 సమీప PFZ', '⚠️ సరిహద్దు తనిఖీ', '🌊 అలల తీవ్రత', '🏠 రేవుకు తిరిగి'],
    },
    'hi': {
      'name': 'हिन्दी',
      'holdToSpeak': 'बोलने के लिए दबाकर रखें',
      'recording': 'सुन रहा है...',
      'minimize': 'नक्शे पर लौटें',
      'advisory': 'समुद्री सुरक्षा सलाह',
      'guardrails': 'सुरक्षा गार्डरेल सक्रिय',
      'details': 'विवरण ▴',
      'sampleQuestion': 'क्या कोई तूफान चेतावनी है? निकटतम PFZ कहां है?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'मौसम सामान्य है (लहरें: 1.3 मीटर, हवा: 12.5 समुद्री मील)। मुख्य मछली पकड़ने का क्षेत्र PFZ-04 14.2 किमी दूर है। सुरक्षित मार्ग लोड है।',
      'sampleAnswerEn': 'Sea state is safe (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-04 is 14.2 km away.',
      'borderStatus': 'अंतर्राष्ट्रीय समुद्री सीमा (IMBL) 4.8 किमी दूर है। आप पूरी तरह सुरक्षित भारतीय जलक्षेत्र में हैं।',
      'borderStatusEn': 'IMBL is 4.8 km away. Craft is inside safe sovereign territorial waters.',
      'weatherStatus': 'लहरें 1.3 मीटर, हवा 12.5 समुद्री मील। मछली पकड़ने के लिए समुद्र अनुकूल है।',
      'weatherStatusEn': 'Wave 1.3m, wind 12.5 kts. Optimal sea conditions.',
      'quickPrompts': ['🐟 निकटतम PFZ', '⚠️ सीमा जांचें', '🌊 लहरों का हाल', '🏠 बंदरगाह लौटें'],
    },
    'bn': {
      'name': 'বাংলা',
      'holdToSpeak': 'কথা বলতে চেপে ধরে রাখুন',
      'recording': 'শুনছি...',
      'minimize': 'মানচিত্রে ফিরুন',
      'advisory': 'সামুদ্রিক নিরাপত্তা বার্তা',
      'guardrails': 'নিরাপত্তা বলয় সক্রিয়',
      'details': 'বিস্তারিত ▴',
      'sampleQuestion': 'ঝড়ের কোনো সতর্কতা আছে কি? নিকটতম PFZ কোথায়?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'সমুদ্র শান্ত রয়েছে (ঢেউ: ১.৩ মি, বাতাস: ১২.৫ নট)। প্রধান মৎস্য শিকার এলাকা PFZ-WB-02 ১৪.২ কিমি দূরে।',
      'sampleAnswerEn': 'Sea conditions calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-WB-02 is 14.2 km away.',
      'borderStatus': 'আন্তর্জাতিক সামুদ্রিক সীমানা (IMBL) ৪.৮ কিমি দূরে। আপনি নিরাপদ ভারতীয় জলসীমায় আছেন।',
      'borderStatusEn': 'IMBL is 4.8 km away. Craft is inside safe waters.',
      'weatherStatus': 'ঢেউয়ের উচ্চতা ১.৩ মি, বাতাস ১২.৫ নট। মাছ ধরার জন্য অনুকূল পরিবেশ।',
      'weatherStatusEn': 'Wave 1.3m, wind 12.5 kts. Optimal fishing conditions.',
      'quickPrompts': ['🐟 নিকটতম PFZ', '⚠️ সীমানা পরীক্ষা', '🌊 ঢেউ পূর্বাভাস', '🏠 বন্দরে ফিরুন'],
    },
    'gu': {
      'name': 'ગુજરાતી',
      'holdToSpeak': 'બોલવા માટે દબાવી રાખો',
      'recording': 'સાંભળી રહ્યું છે...',
      'minimize': 'નકશા પર પાછા જાઓ',
      'advisory': 'દરિયાઈ સુરક્ષા સલાહ',
      'guardrails': 'સુરક્ષા ગાર્ડરેલ સક્રિય',
      'details': 'વિગતો ▴',
      'sampleQuestion': 'વાવાઝોડાની ચેતવણી છે? નજીકનું PFZ ક્યાં છે?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'દરિયો શાંત છે (મોજાં: ૧.૩ મીટર, પવન: ૧૨.૫ નોટ્સ). મુખ્ય મત્સ્ય ઝોન PFZ-GJ-06 ૧૪.૨ કિમી દૂર છે.',
      'sampleAnswerEn': 'Sea is calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-GJ-06 is 14.2 km away.',
      'borderStatus': 'આંતરરાષ્ટ્રીય દરિયાઈ સરહદ (IMBL) ૪.૮ કિમી દૂર છે. તમે સુરક્ષિત ભારતીય જળસીમામાં છો.',
      'borderStatusEn': 'IMBL is 4.8 km away. Craft is inside safe territorial waters.',
      'weatherStatus': 'મોજાંની ઊંચાઈ ૧.૩ મીટર, પવન ૧૨.૫ નોટ્સ. માછીમારી માટે ઉત્તમ સ્થિતિ.',
      'weatherStatusEn': 'Wave 1.3m, wind 12.5 kts. Favorable conditions.',
      'quickPrompts': ['🐟 નજીકનું PFZ', '⚠️ સરહદ ચકાસો', '🌊 મોજાંની આગાહી', '🏠 બંદરે પાછા'],
    },
    'ml': {
      'name': 'മലയാളം',
      'holdToSpeak': 'സംസാരിക്കാൻ അമർത്തിപ്പിടിക്കുക',
      'recording': 'കേൾക്കുന്നു...',
      'minimize': 'മാപ്പിലേക്ക് മടങ്ങുക',
      'advisory': 'തീരദേശ സുരക്ഷാ നിർദ്ദേശം',
      'guardrails': 'സുരക്ഷാ മാനദണ്ഡങ്ങൾ സജീവം',
      'details': 'വിശദാംശങ്ങൾ ▴',
      'sampleQuestion': 'ചുഴലിക്കാറ്റ് മുന്നറിയിപ്പുണ്ടോ? അടുത്തുള്ള PFZ എവിടെ?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'കടൽ ശാന്തമാണ് (തിരമാല: 1.3 മീറ്റർ, കാറ്റ്: 12.5 നോട്ട്). പ്രധാന മത്സ്യബന്ധന മേഖല PFZ-KL-03 14.2 കി.മീ അകലെയാണ്.',
      'sampleAnswerEn': 'Sea state calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-KL-03 is 14.2 km away.',
      'borderStatus': 'അന്താരാഷ്ട്ര സമുദ്ര അതിർത്തി (IMBL) 4.8 കി.മീ അകലെയാണ്. നിങ്ങൾ സുരക്ഷിത മേഖലയിലാണ്.',
      'borderStatusEn': 'IMBL is 4.8 km away. Safe territorial waters.',
      'weatherStatus': 'തിരമാല 1.3 മീറ്റർ, കാറ്റ് 12.5 നോട്ട്. മീൻപിടുത്തത്തിന് അനുകൂലമായ കാലാവസ്ഥ.',
      'weatherStatusEn': 'Wave 1.3m, wind 12.5 kts. Optimal sea conditions.',
      'quickPrompts': ['🐟 അടുത്തുള്ള PFZ', '⚠️ അതിർത്തി പരിശോധിക്കുക', '🌊 തിരമാലകൾ', '🏠 തുറമുഖത്തേക്ക്'],
    },
    'or': {
      'name': 'ଓଡ଼ିଆ',
      'holdToSpeak': 'କହିବା ପାଇଁ ଚାପି ଧରନ୍ତୁ',
      'recording': 'ଶୁଣୁଛି...',
      'minimize': 'ମାନଚିତ୍ରକୁ ଯାଆନ୍ତୁ',
      'advisory': 'ସାମୁଦ୍ରିକ ସୁରକ୍ଷା ପରାମର୍ଶ',
      'guardrails': 'ସୁରକ୍ଷା ନିୟମ ସକ୍ରିୟ',
      'details': 'ବିବରଣୀ ▴',
      'sampleQuestion': 'ବାତ୍ୟା ସତର୍କତା ଅଛି କି? ନିକଟତମ PFZ କେଉଁଠାରେ?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'ସମୁଦ୍ର ଶାନ୍ତ ରହିଛି (ତରଙ୍ଗ: ୧.୩ ମିଟର, ପବନ: ୧୨.୫ ନଟ୍)। ମୁଖ୍ୟ ମତ୍ସ୍ୟ କ୍ଷେତ୍ର PFZ-OD-01 ୧୪.୨ କିମି ଦୂରରେ ଅଛି।',
      'sampleAnswerEn': 'Sea conditions calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-OD-01 is 14.2 km away.',
      'borderStatus': 'ଅନ୍ତର୍ଜାତୀୟ ସାମୁଦ୍ରିକ ସୀମା (IMBL) ୪.୮ କିମି ଦୂର। ଆପଣ ସୁରକ୍ଷିତ ଭାରତୀୟ ଜଳସୀମାରେ ଅଛନ୍ତି।',
      'borderStatusEn': 'IMBL is 4.8 km away. Inside safe territorial waters.',
      'weatherStatus': 'ତରଙ୍ଗ ୧.୩ ମିଟର, ପବନ ୧୨.୫ ନଟ୍। ମାଛ ଧରିବା ପାଇଁ ଅନୁକୂଳ ପରିବେଶ।',
      'weatherStatusEn': 'Wave 1.3m, wind 12.5 kts. Favorable conditions.',
      'quickPrompts': ['🐟 ନିକଟତମ PFZ', '⚠️ ସୀମା ଯାଞ୍ଚ', '🌊 ସମୁଦ୍ର ତରଙ୍ଗ', '🏠 ବନ୍ଦର ଫେରନ୍ତୁ'],
    },
    'en': {
      'name': 'English',
      'holdToSpeak': 'Hold to Speak',
      'recording': 'Listening...',
      'minimize': 'MINIMIZE TO MAP',
      'advisory': 'MARINE ADVISORY',
      'guardrails': 'Guardrails Active',
      'details': 'Details ▴',
      'sampleQuestion': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleQuestionEn': 'Is there a storm alert? Where is the nearest PFZ?',
      'sampleAnswer': 'Sea conditions calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-TN-04 is 14.2 km away. Safe route loaded.',
      'sampleAnswerEn': 'Sea conditions calm (Wave: 1.3m, Wind: 12.5 kts). Optimal fishing zone PFZ-TN-04 is 14.2 km away.',
      'borderStatus': 'Border status: IMBL is 4.8 km away. Craft is inside safe sovereign territorial waters.',
      'borderStatusEn': 'Border status: IMBL is 4.8 km away. Craft is inside safe sovereign territorial waters.',
      'weatherStatus': 'Wave height 1.3m, wind 12.5 kts. Optimal sea conditions for fishing.',
      'weatherStatusEn': 'Wave height 1.3m, wind 12.5 kts. Optimal sea conditions for fishing.',
      'quickPrompts': ['🐟 Nearest PFZ', '⚠️ Check Border', '🌊 Sea Waves', '🏠 Return Port'],
    },
  };

  static Map<String, dynamic> of(String code) {
    return _data[code] ?? _data['en']!;
  }
}
